auth:
  azure:
    clientID: 427752a8-ec94-4994-89fd-3c1bad7d45c9
    clientSecret: "[5jC0zTtIzbvIAM53]S+rKkzkOH=v7:2"
    redirectUrlHost: http://localhost:8080
    tenantID: 8b7425f8-ed1a-4703-b748-5d8aa9d83471
    scopes: openid

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AzureAuthClient
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
